#!/bin/sh

# package manager
# uname -r | grep arch > /dev/null 2>&1
# if [ $? == 0 ]; then
  # alias upg='sudo pacman -Syu'
# fi

alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

alias ll='exa -lah --group-directories-first'
alias cls='clear'
alias mkdir='mkdir -pv'
alias gs='git status'
alias o='xdg-open'
alias cat='bat'
alias mux='tmux attach -t Z'
