# load zsh configuration
for file in ~/.config/zsh/*; do
    source "$file"
done

# aliases
if [ -f ~/.aliases ]; then
  source ~/.aliases;
fi
if [ -f ~/.aliases_local ]; then
  source ~/.aliases_local;
fi
